config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  resources :posts do
    resources :comments, only: [:create, :destroy] do
      resources :comment_likes, only: [:create, :destroy] 
    end
    resources :post_likes, only: [:create, :destroy]
  end
  get 'test' => 'posts#test'
  get 'test2' => 'posts#test2'
  get 'test3' => 'posts#test3'
  get 'test4' => 'posts#test4'
  get 'test5' => 'posts#test5'
  get 'test6' => 'posts#test6'
  get 'test7' => 'posts#test7'
  

  root 'posts#index'
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: 'User'
    belongs_to :follower, class_name: 'User'

    validates :following_id, presence: true
    validates :follower_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        current_user.follow(params[:user_id])
    end

    def destroy
        @user = User.find(params[:user_id])
        current_user.unfollow(params[:user_id])
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<% if current_user.following?(user) %>
    <%= link_to user_relationship_path(id:user.id, user_id:user.id), method: :delete, remote: true do %>
        <i class="fas fa-handshake"></i>
    <% end %>
<% else %>
    <%= link_to user_relationships_path(id:user.id, user_id:user.id), method: :post, remote: true do %>
        <i class="far fa-handshake"></i>
    <% end %>
<% end %>

app/views/relationships/create.js.erb
$('#relationships_buttons_<%= @user.id %>').html("<%= j(render partial: 'relationships/follow', locals: {user: @user}) %>");

app/views/relationships/destroy.js.erb
$('#relationships_buttons_<%= @user.id %>').html("<%= j(render partial: 'relationships/follow', locals: {user: @user }) %>");