config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  resources :posts do
    resources :comments, only: [:create, :destroy] do
      resources :comment_likes, only: [:create, :destroy] 
    end
    resources :post_likes, only: [:create, :destroy]
  end
  get 'test' => 'posts#test'
  get 'test2' => 'posts#test2'
  get 'test3' => 'posts#test3'
  get 'test4' => 'posts#test4'
  get 'test5' => 'posts#test5'
  get 'test6' => 'posts#test6'
  get 'test7' => 'posts#test7'
  

  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :comments, dependent: :destroy
    has_many :post_likes, dependent: :destroy
    has_many :post_liked_users, through: :post_likes, source: :post
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        if params[:search] != nil && params[:search] != ""
            search = params[:search]
            @posts = Post.joins(:user).where("body LIKE ? OR name LIKE ?", "%#{search}%", "%#{search}%")
        else
            @posts = Post.all
        end
        @comment = Comment.new
    end
    def show
        @post = Post.find(params[:id])
        @comments = Comment.all
        @comment = Comment.new
        @comment.post_id = params[:id]
    end
    def new
        @post = Post.new
    end
    def create
        post = Post.new(posts_params)
        post.user_id = current_user.id
        if post.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    def edit
        @post = Post.find(params[:id])
    end
    def update
        post = Post.find(params[:id])
        if post.update(posts_params)
            redirect_to :action => "show", :id => post.id
        else
            redirect_to :action => "edit", :id => post.id
        end
    end
    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to :action => "index"
    end
    def test7
        @posts = Post.all
        @array = Array.new
        @array2 = Array.new
        @posts.each do |p|
            @array[p.id] = { "key1" => p.body, "key2" => p.id }
            @array2.push({ "key1" => p.body, "key2" => p.id })
        end
    end

    private
    def posts_params
        params.require(:post).permit(:body, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="new-main-container">
    <%= form_with model: @post do |f| %>
        <div class="new-body-field">
            <%= f.label :コメント %>
            <%= f.text_field :body, :size => 140, class:"new-bodyform-field" %>
        </div>
        <div class="field">
            <%= f.label :画像 %>
            <%= f.file_field :image %>
        </div>
        <%= f.submit "投稿する", class:"btn btn-primary" %>
    <% end %>
</div>
<style>
    .new-main-container {
        width: 50%;
        margin: 0px auto;
    }
    .new-bodyform-field {
        width: 100%;
    }
</style>

app/views/posts/index.html.erb
<style>
.undisplay-field {
    display: none;
}  
.icons {
    width: 100%;
}
.icon-box {
    display: flex;
    justify-content: space-around;
    padding: 0px;
}
.icon {
    background-color: #fff;
    border: none;
}
.index-commentform-field {
    width: 100%;
}
#explain-box {
    position: absolute;
    top: 100px;
    left: 0px;
    border: solid 1px;
    background: white;
    font-size: 10px;
}
.undisplay {
    display: none;
}
</style>
<script>
history.replaceState(null, document.getElementsByTagName('title')[0].innerHTML, null);
window.addEventListener('popstate', function(e) {
  window.location.reload();
});
</script>

<div class="container">
    <div class="row">
        <h3>投稿を検索する</h3>
        <%= form_with url: posts_path, method: :get do |f| %>
            <%= f.text_field :search %>
            <%= f.submit '検索' %>
        <% end %>
    </div>
    <div class="row">
        <% @posts.each do |post| %>
            <div class="col-sm-3 card">
                <%= image_tag post.image_url class:"card-img-top"%>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to user_path(post.user_id) do %>
                            <%= image_tag post.user.image_url, size: "50x50", class:"rounded-circle" if post.user.image? %>
                            <%= post.user.name %><br>
                        <% end %>
                    </h5>
                    <p class="card-text">
                    <%= post.body %>
                    </p>
                    <div class="icons container">
                        <div class="row">
                            <div class="col-3 icon-box">
                                <div id="post_likes_buttons_<%= post.id %>">
                                    <%= render partial: 'post_likes/like', locals: { post: post } %>
                                </div>
                            </div>
                            <div class="col-3 icon-box">
                                <%= link_to  post_path(post.id) do %>
                                    <i class="fas fa-file-alt show-icon"></i>
                                <% end %>
                            </div>
                            <% if user_signed_in? && current_user.id == post.user_id %>
                                <div class="col-3 icon-box">
                                    <%= link_to edit_post_path(post.id) do %>
                                        <i class="fas fa-pen edit-icon"></i>
                                    <% end %>
                                </div>
                                <div class="col-3 icon-box">
                                    <%= link_to post_path(post.id), method: :delete, data: { confirm: '削除しますか？' } do %>
                                        <i class="fas fa-trash-alt delete-icon"></i>
                                    <% end %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                    <% @comment.post_id = post.id %>
                    <div class="container">
                        <%= form_with(model: [post, @comment]) do |f| %>
                            <div class="row">
                                <div class="col-9">
                                    <div class="index-comment-field">
                                        <%= f.text_field :body, :placeholder => "コメント", class:"index-commentform-field" %>
                                    </div>
                                </div>
                                <div class="undisplay-field">
                                    <%= f.label :post_id %>
                                    <%= f.text_field :post_id %>
                                </div>
                                <div class="col-1">
                                    <%= button_tag type: :submit, class:"icon" do %>
                                        <i class="far fa-comment"></i>
                                    <% end %> 
                                </div>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>
</body>

<script>
    const showIcons = document.querySelectorAll('.show-icon')
    const editIcons = document.querySelectorAll('.edit-icon')
    const deleteIcons = document.querySelectorAll('.delete-icon')

    function myFunc(elements, explain){
        elements.forEach((value, index) => {
            value.addEventListener('mouseenter', () => {
                const divElement = document.createElement('div');
                divElement.id = 'explain-box';
                divElement.classList.add('undisplay')
                divElement.innerHTML = explain;
                document.body.appendChild(divElement);
                const explainBox = document.querySelector('#explain-box');
                document.addEventListener('mousemove', onMouseMove);
                function onMouseMove(event) {
                    explainBox.style.left = `${event.clientX + 5}px`;
                    explainBox.style.top = `${event.clientY - 20}px`;
                }
                setTimeout(() => {
                    divElement.classList.remove('undisplay')
                }, 1000);
            });
            value.addEventListener('mouseleave', () => {
                setTimeout(() => {
                    const divElement = document.getElementById('explain-box');
                    divElement.remove();
                }, 0);
            });
        });
    };

    myFunc(showIcons, "詳細へ");
    myFunc(editIcons, "投稿を編集する");
    myFunc(deleteIcons, "投稿を削除する");


</script>

app/views/posts/new.html.erb
<div class="new-main-container">
    <%= form_with model: @post do |f| %>
        <div class="new-body-field">
            <%= f.label :コメント %>
            <%= f.text_field :body, :size => 140, class:"new-bodyform-field" %>
        </div>
        <div class="field">
            <%= f.label :画像 %>
            <%= f.file_field :image %>
        </div>
        <%= f.submit "投稿する", class:"btn btn-primary" %>
    <% end %>
</div>
<style>
    .new-main-container {
        width: 50%;
        margin: 0px auto;
    }
    .new-bodyform-field {
        width: 100%;
    }
</style>

app/views/posts/show.html.erb
<style>
.undisplay-field {
    display: none;
}
.main-container {
    margin: 0px auto;
    width: 80%;
}
.icons {
    width: 100%;
}
.icon-box {
    display: flex;
    justify-content: space-around;
}
.icon {
    background-color: #fff;
    border: none;
    color: black;
}
.main {
    width: 50%;
}
.comment-container {
    border-bottom: 1px solid;
}
.name-box {
    display: flex;
    align-items: center;
}
.post-commentform-field {
    width: 100%;
}
#explain-box {
    position: absolute;
    top: 100px;
    left: 0px;
    border: solid 1px;
    background: white;
    font-size: 10px;
}
.undisplay {
    display: none;
}
</style>
<div class="main container">
    <div class="row">
        <div class="col-1">
            <%= image_tag @post.user.image_url, size: "50x50", class:"rounded-circle" if @post.user.image? %>
        </div>
        <div class="col-11 name-box">
            <%= link_to user_path(@post.user_id) do %>
                <%= @post.user.name %><br>
            <% end %>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <%= @post.body %>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="icons container">
                <div class="row">
                    <div class="col-3 icon-box">
                        <div id="post_likes_buttons_<%= @post.id %>">
                            <%= render partial: 'post_likes/like', locals: { post: @post } %>
                        </div>
                    </div>
                    <div class="col-3 icon-box">
                        <%= link_to  post_path(@post.id) do %>
                            <i class="fas fa-file-alt show-icon"></i>
                        <% end %>
                    </div>
                    <% if user_signed_in? && current_user.id == @post.user_id %>
                        <div class="col-3 icon-box">
                            <%= link_to edit_post_path(@post.id) do %>
                                <i class="fas fa-pen edit-icon"></i>
                            <% end %>
                        </div>
                        <div class="col-3 icon-box">
                            <%= link_to post_path(@post.id), method: :delete, data: { confirm: '削除しますか？' } do %>
                                <i class="fas fa-trash-alt delete-icon"></i>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <%= image_tag @post.image_url, size: "500x500" if @post.image? %>
        </div>
    </div>
    <% @post.comments.each do |comment| %>
        <div class="row comment-container">
            <div class="col-1">
                <%= image_tag comment.user.image_url, size: "50x50", class:"rounded-circle" if comment.user.image? %>
            </div>
            <div class="col-5">
                <%= comment.user.name %><br>
                <%= comment.body %>
            </div>
            <div class="col-3">
                <div class="icons container">
                    <div class="row">
                        <div class="col-6 icon-box">
                            <div id="comment_likes_buttons_<%= comment.id %>">
                                <%= render partial: 'comment_likes/like', locals: { comment: comment, post: @post } %>
                            </div>
                        </div>
                        <div class="col-6 icon-box">
                            <% if user_signed_in? && current_user.id == comment.user_id %>
                                <%= link_to post_comment_path(post_id:@post.id ,id:comment.id), method: :delete, data: { confirm: '削除しますか？' } do %>
                                    <i class="fas fa-trash-alt"></i>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    <%= form_with(model: [@post, @comment]) do |f| %>
    <div class="row">
        <div class="col-11">
            <div class="post-comment-field">
                <%= f.text_field :body, :placeholder => "コメントを入力して下さい", :size => 140, class:"post-commentform-field" %>
            </div>
        </div>
        <div class="undisplay-field">
            <%= f.text_field :post_id %>
        </div>
        <div class="col-1">
            <%= button_tag type: :submit, class:"icon" do %>
                <i class="far fa-comment"></i>
            <% end %>
        </div>
    </div>
<% end %>
</div>

<script>
    const showIcon = document.querySelector('.show-icon')
    const editIcon = document.querySelector('.edit-icon')
    const deleteIcon = document.querySelector('.delete-icon')

    function myFunc(element, explain){
        element.addEventListener('mouseenter', () => {
            const divElement = document.createElement('div');
            divElement.id = 'explain-box';
            divElement.classList.add('undisplay')
            divElement.innerHTML = explain;
            document.body.appendChild(divElement);
            const explainBox = document.querySelector('#explain-box');
            document.addEventListener('mousemove', onMouseMove);
            function onMouseMove(event) {
                explainBox.style.left = `${event.clientX + 5}px`;
                explainBox.style.top = `${event.clientY - 20}px`;
            }
            setTimeout(() => {
                divElement.classList.remove('undisplay')
            }, 1000);
        });
        element.addEventListener('mouseleave', () => {
            setTimeout(() => {
                const divElement = document.getElementById('explain-box');
                divElement.remove();
            }, 0);
        });
    };

    myFunc(showIcon, "詳細へ");
    myFunc(editIcon, "投稿を編集する");
    myFunc(deleteIcon, "投稿を削除する");


</script>

app/views/posts/test.html.erb
<div class=bird>
    <div class="beak1">
        <div class="beak1-element1"></div>
        <div class="beak1-element2"></div>
    </div>
    <div class="beak2">
        <div class="beak2-element1"></div>
        <div class="beak2-element2"></div>
    </div>
    <div class="body">
        <div class="body-element1"></div>
        <div class="body-element2"></div>
    </div>
    <div class="head">
        <div class="head-element"></div>
    </div>
    <div class="wing1">
        <div class="wing1-element1"></div>
        <div class="wing1-element2"></div>
    </div>
    <div class="wing2">
        <div class="wing2-element1"></div>
        <div class="wing2-element2"></div>
    </div>
    <div class="wing3">
        <div class="wing3-element1"></div>
        <div class="wing3-element2"></div>
    </div>
</div>

<style>
    .bird {
        margin: 0px auto;
        position: relative;
        height: 10vh;
        width: 10vh;
        background-color: white;
    }
    .beak1 {
        position: absolute;
        top: -4.1vh;
        left: 7.4vh;
        height: 10vh;
        width: 10vh;
        border-radius: 50%;
        background-color: transparent;
        overflow: hidden;
    }
    .beak1-element1 {
        position: absolute;
        background-color: rgb(25, 165, 247);
        height: 300%;
        width: 300%;
        top: -200%;
        left: -230%;
        border-radius: 50%;
    }
    .beak1-element2 {
        position: absolute;
        background-color: white;
        height: 320%;
        width: 320%;
        top: -251%;
        left: -180%;
        border-radius: 50%;
    }
    .beak2 {
        position: absolute;
        top: -4.6vh;
        left: 7.2vh;
        height: 10vh;
        width: 10vh;
        border-radius: 50%;
        background-color: transparent;
        overflow: hidden;
    }
    .beak2-element1 {
        position: absolute;
        background-color: rgb(25, 165, 247);
        height: 300%;
        width: 300%;
        top: -200%;
        left: -229%;
        border-radius: 50%;
    }
    .beak2-element2 {
        position: absolute;
        background-color: white;
        height: 320%;
        width: 320%;
        top: -251%;
        left: -179%;
        border-radius: 50%;
    }
    .body {
        position: absolute;
        top: 3vh;
        left: 0vh;
        height: 10vh;
        width: 10vh;
        background-color: transparent;
        overflow: hidden;
    }
    .body-element1 {
        position: absolute;
        background-color: rgb(25, 165, 247);
        height: 85%;
        width: 85%;
        top: -35%;
        left: -3%;
        border-radius: 50%;
    }
    .body-element2 {
        position: absolute;
        background-color: white;
        height: 100%;
        width: 100%;
        top: -50%;
        left: -50%;
        border-radius: 50%;
    }
    .head {
        position: absolute;
        top: -7vh;
        left: 0vh;
        height: 10vh;
        width: 10vh;
        background-color: transparent;
        overflow: hidden;
    }
    .head-element {
        position: absolute;
        background-color: rgb(25, 165, 247);
        height: 31.8%;
        width: 31.8%;
        top: 85%;
        left: 50%;
        border-radius: 50%;
    }
    .wing1 {
        position: absolute;
        top: -2vh;
        left: -5vh;
        height: 10vh;
        width: 10vh;
        border-radius: 50%;
        background-color: transparent;
        overflow: hidden;
    }
    .wing1-element1 {
        position: absolute;
        background-color: rgb(25, 165, 247);
        height: 40%;
        width: 60%;
        top: 50%;
        left: 65%;
        border-radius: 50%;
    }
    .wing1-element2 {
        position: absolute;
        background-color: white;
        height: 300%;
        width: 300%;
        top: -220%;
        left: -85%;
        border-radius: 50%;
    }
    .wing2 {
        position: absolute;
        top: -2vh;
        left: -5vh;
        height: 10vh;
        width: 10vh;
        background-color: transparent;
        border-radius: 50%;
        overflow: hidden;
    }
    .wing2-element1 {
        position: absolute;
        background-color: rgb(25, 165, 247);
        height: 40%;
        width: 40%;
        top: 41%;
        left: 64%;
        border-radius: 50%;
    }
    .wing2-element2 {
        position: absolute;
        background-color: white;
        height: 300%;
        width: 300%;
        top: -233%;
        left: -87%;
        border-radius: 50%;
    }
    .wing3 {
        position: absolute;
        top: -2vh;
        left: -5vh;
        height: 10vh;
        width: 10vh;
        background-color: transparent;
        border-radius: 50%;
        overflow: hidden;
    }
    .wing3-element1 {
        position: absolute;
        background-color: rgb(25, 165, 247);
        height: 42%;
        width: 50%;
        top: 30%;
        left: 63%;
        border-radius: 50%;
    }
    .wing3-element2 {
        position: absolute;
        background-color: white;
        height: 30%;
        width: 60%;
        top: 25%;
        left: 63%;
        border-radius: 50%;
    }
</style>

app/views/posts/test2.html.erb
<style>
//import font from google
@import url(https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900);

//import compass
@import "compass";

//colors
$primary-color   : #FF512F;
$secondary-color : #333;
$form-bg         : #fff;


//contact form
.contact-form{
    margin-top: 30px;
}
    .input-block{
        background-color: rgba(white, .8);
        border: solid 1px $primary-color;
        width: 100%;
        height: 60px;
        padding: 25px;
        position: relative;
        margin-bottom: 20px;
        @include transition(all 0.3s ease-out);
        &.focus{
            background-color: $form-bg;
            border: solid 1px darken($primary-color, 10%);
        }
        &.textarea{
            height: auto;
            .form-control{
                height: auto;
                resize: none;
            }
        }
        label{
            position: absolute;
            left: 25px;
            top: 25px;
            display: block;
            margin: 0;
            font-weight: 300;
            z-index: 1;
            color: $secondary-color;
            font-size: 50px;
            line-height: 10px;
        }
        .form-control{
            background-color: transparent;
            padding: 0;
            border: none;
            @include border-radius(0);
            @include box-shadow(none);
            height: auto;
            position: relative;
            z-index: 2;
            font-size: 18px;
            color: $secondary-color;
        }
        .form-control:focus{
            label{
                top: 0;
            }
        }
    }
    .square-button{
        background-color: rgba(white, .8);
        color: darken($primary-color, 10%);
        font-size: 26px;
        text-transform: uppercase;
        font-weight: 700;
        text-align: center;
        @include border-radius(2px);
        @include transition(all 0.3s ease);
        padding: 0 60px;
        height: 60px;
        border: none;
        width: 100%;
        &:hover,
        &:focus{
            background-color: white;
        }
    }


//tablet and above devices
@media (min-width: 768px) { 
  .contact-wrap{
    width: 60%;
    margin: auto;
  }
}




//////////////////////////
  /*----page styles---*/
//////////////////////////
body{
  @include background-image(linear-gradient(to right, $primary-color, #DD2476));
  font-family: 'Roboto', sans-serif;
}
.contact-wrap{
  padding: 15px;
}

h1{
  background-color: white;
  color: lighten($primary-color, 10%);
  padding: 40px;
  margin: 0 0 50px;
  font-size: 30px;
  text-transform: uppercase;
  font-weight: 700;
  text-align: center;
  small{
    font-size: 18px;
    display: block;
    text-transform: none;
    font-weight: 300;
    margin-top: 10px;
    color: lighten($primary-color, 10%);
  }
}


//follow me template
.made-with-love{
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
  i{
    font-style: normal;
    color: #F50057;
    font-size: 14px;
    position: relative;
    top: 2px;
  }
  a{
    color: #fff;
    text-decoration: none;
    &:hover{
      text-decoration: underline;
    }
  }
}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
//material contact form animation
$('.contact-form').find('.form-control').each(function() {
  var targetItem = $(this).parent();
  if ($(this).val()) {
    $(targetItem).find('label').css({
      'top': '10px',
      'fontSize': '14px'
    });
  }
})
$('.contact-form').find('.form-control').focus(function() {
  $(this).parent('.input-block').addClass('focus');
  $(this).parent().find('label').animate({
    'top': '10px',
    'fontSize': '14px'
  }, 300);
})
$('.contact-form').find('.form-control').blur(function() {
  if ($(this).val().length == 0) {
    $(this).parent('.input-block').removeClass('focus');
    $(this).parent().find('label').animate({
      'top': '25px',
      'fontSize': '18px'
    }, 300);
  }
})

</script>

<h1> Responsive Material Design Form 
  <small>Material Design delivers a cleaner and flatter user interface</small>
</h1>
<section class="contact-wrap">
  <form action="" class="contact-form">
    <div class="col-sm-6">
      <div class="input-block">
        <label for="">First Name</label>
        <input type="text" class="form-control">
      </div>
    </div>
    <div class="col-sm-6">
      <div class="input-block">
        <label for="">Last Name</label>
        <input type="text" class="form-control">
      </div>
    </div>
    <div class="col-sm-12">
      <div class="input-block">
        <label for="">Email</label>
        <input type="text" class="form-control">
      </div>
    </div>
    <div class="col-sm-12">
      <div class="input-block">
        <label for="">Message Subject</label>
        <input type="text" class="form-control">
      </div>
    </div>
    <div class="col-sm-12">
      <div class="input-block textarea">
        <label for="">Drop your message here</label>
        <textarea rows="3" type="text" class="form-control"></textarea>
      </div>
    </div>
    <div class="col-sm-12">
      <button class="square-button">Send</button>
    </div>
  </form>
</section>

<!-- follow me template -->
<div class="made-with-love">
  Made with 
  <i>♥</i> by 
  <a target="_blank" href="https://codepen.io/nikhil8krishnan">Nikhil Krishnan</a>
</div>

app/views/posts/test3.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(function() {



$("#small-btn").click(function() {
 
$(".textbox").css("font-size", "12px");
 
});
 
$("#middle-btn").click(function() {
 
$(".textbox").css("font-size", "24px");
 
});
 
$("#big-btn").click(function() {
 
$(".textbox").css("font-size", "50px");
 
});
 
});

alert('OK!');

</script>

<button id=”small-btn”>小</button>

<button id=”middle-btn”>中</button>

<button id=”big-btn”>大</button>

<p class=”textbox”>本文</p>

app/views/posts/test5.html.erb
<style>
#anime_test{
    height: 100px;
    width: 100px;
    background-color: #F44336;
    position: relative;
    left: 0;
    transition: 2.5s;
}
#anime_test.active {
    background-color: #2196F3;
    left: calc(100% - 100px);
}

.anime_test-btn {
    margin-top:  10px;
    display:  inline-block;
    padding:  5px 10px;
    border: solid 1px;
    cursor:  pointer;
}
</style>
<script>
function clickTest() {
      target = document.getElementById("anime_test");
      if (target.className == null || target.className=="") {
        target.className = "active";
      } else {
        target.className = "";
      }
    }
</script>
<div id="anime_test">
</div>
<div class="anime_test-btn" onclick="clickTest();">
    ボタン
</div>

app/views/posts/test6.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          投稿
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "投稿一覧へ", posts_path, class:"dropdown-item" %>
          <a class="dropdown-item" href="/posts/new">新規投稿</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/posts/test7.html.erb
<style>
@import url(../../common/css/base_photo.css);
body {
  background-size: cover;
  background: url("../common/bg_nature.jpg") center;
}

.character {
  position: absolute;
  top: 0;
  left: 0;
}
#character2 {
  position: absolute;
  height: 100px;
  width: 100px;
  background-color: red;
}
</style>

<body>
<!-- 動かしたいキャラクター画像 -->
<div class="character">
</div>
<div id="character2"></div>
</body>
<script>
/** 動かしたいキャラクター */
const character = document.querySelector('#character2');

// ページ上でマウスボタンを押したら、キャラクターの移動開始
document.addEventListener('mousedown', () => {
  // マウスの動きに合わせてキャラクターを動かす
  document.addEventListener('mousemove', onMouseMove);

  // ページ上でマウスボタンを離したら、キャラクターの移動を終了
  document.addEventListener('mouseup', () => {
    document.removeEventListener('mousemove', onMouseMove);
  });
});

/**
 * マウスが動いた時の処理
 */
function onMouseMove(event) {
  character.style.left = `${event.clientX - 100}px`;
  character.style.top = `${event.clientY - 100}px`;
}
</script>