config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  resources :posts do
    resources :comments, only: [:create, :destroy] do
      resources :comment_likes, only: [:create, :destroy] 
    end
    resources :post_likes, only: [:create, :destroy]
  end
  get 'test' => 'posts#test'
  get 'test2' => 'posts#test2'
  get 'test3' => 'posts#test3'
  get 'test4' => 'posts#test4'
  get 'test5' => 'posts#test5'
  get 'test6' => 'posts#test6'
  get 'test7' => 'posts#test7'
  

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
    has_many :comment_likes, dependent: :destroy
    has_many :comment_liked_users, through: :comment_likes, source: :comment
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :comment
  belongs_to :user

  validates_uniqueness_of :comment_id, scope: :user_id
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :comments, dependent: :destroy
    has_many :post_likes, dependent: :destroy
    has_many :post_liked_users, through: :post_likes, source: :post
end

app/models/post_like.rb
class PostLike < ApplicationRecord
    belongs_to :user
    belongs_to :post

    validates_uniqueness_of :post_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: 'User'
    belongs_to :follower, class_name: 'User'

    validates :following_id, presence: true
    validates :follower_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  validates :name, presence: true
  mount_uploader :image, ImageUploader

  has_many :posts, dependent: :destroy
  has_many :post_likes, dependent: :destroy
  has_many :post_liked_posts, through: :post_likes, source: :post
  def already_post_liked?(post)
    self.post_likes.exists?(post_id: post.id)
  end
  has_many :comment_likes, dependent: :destroy
  has_many :comment_liked_comments, through: :comment_likes, source: :comment
  def already_comment_liked?(comment)
    self.comment_likes.exists?(comment_id: comment.id)
  end

  has_many :relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  has_many :followers, through: :reverse_of_relationships, source: :following
  def follow(user_id)
    relationships.create(follower_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(follower_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        if params[:search] != nil && params[:search] != ""
            search = params[:search]
            @posts = Post.joins(:user).where("body LIKE ? OR name LIKE ?", "%#{search}%", "%#{search}%")
        else
            @posts = Post.all
        end
        @comment = Comment.new
    end
    def show
        @post = Post.find(params[:id])
        @comments = Comment.all
        @comment = Comment.new
        @comment.post_id = params[:id]
    end
    def new
        @post = Post.new
    end
    def create
        post = Post.new(posts_params)
        post.user_id = current_user.id
        if post.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    def edit
        @post = Post.find(params[:id])
    end
    def update
        post = Post.find(params[:id])
        if post.update(posts_params)
            redirect_to :action => "show", :id => post.id
        else
            redirect_to :action => "edit", :id => post.id
        end
    end
    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to :action => "index"
    end
    def test7
        @posts = Post.all
        @array = Array.new
        @array2 = Array.new
        @posts.each do |p|
            @array[p.id] = { "key1" => p.body, "key2" => p.id }
            @array2.push({ "key1" => p.body, "key2" => p.id })
        end
    end

    private
    def posts_params
        params.require(:post).permit(:body, :image)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!
    def create
        @room = Room.create
        @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
        @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
        redirect_to "/rooms/#{@room.id}"
    end

    def show
        @room = Room.find(params[:id])
        if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
            @messages = @room.messages
            @message = Message.new
            @entries = @room.entries
        else
            redirect_back(fallback_location: root_path)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/post_likes_helper.rb
module PostLikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekInstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand">GeekInstagram</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                投稿
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "投稿一覧", posts_path, class:"dropdown-item" %>
                <%= link_to "新規投稿", new_post_path, class:"dropdown-item" %>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if user_signed_in? %>
                  <%= current_user.name %>
                <% else %>
                  ユーザー
                <% end %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% if user_signed_in? %>
                  <%= link_to "マイページ", user_path(current_user.id), class:"dropdown-item" %>
                  <div class="dropdown-divider"></div>
                  <%= link_to "ログアウト", destroy_user_session_path, class:"dropdown-item", method: :delete %>
                <% else %>
                  <%= link_to "ログイン", new_user_session_path, class:"dropdown-item" %>
                  <%= link_to "新規会員登録", new_user_registration_path, class:"dropdown-item" %>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>